channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7
  - pip<=25.1
  - numpy=1.26.4
  - pandas=2.3.0
  - scikit-learn=1.5.2
  - scipy=1.15.3
  - matplotlib=3.10.3
  - seaborn=0.13.2
  - pip:
    - mlflow==2.19.0
    - cloudpickle==3.1.1
    - psutil==7.0.0
    - dagshub==0.5.10
    - PyYAML==6.0.2
name: mlflow-env
